import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"], // Define font weights you need
  subsets: ["latin"],
  variable: "--font-Poppins-sans", // Define the custom CSS variable
});

export const metadata: Metadata = {
  title: "DigiFly",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>; // Handle async params correctly
}) {
  // Await params to resolve the promise
  const { locale } = await params;

  return (
    <html lang={locale || "en"}>
      <body className={`${poppins.variable} antialiased bg-[#FCFCFE]`}>
        {children}
      </body>
    </html>
  );
}
